// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAguCrxsjmRxZ6Xyte7iI1Uhk25XfT0Gk',
    appId: '1:811652518412:web:5c7789f193042c1f3e9429',
    messagingSenderId: '811652518412',
    projectId: 'flash-chat-f2ed3',
    authDomain: 'flash-chat-f2ed3.firebaseapp.com',
    storageBucket: 'flash-chat-f2ed3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD69Z4igDNCbywRFUpO7z8t7z6MhvIR_V4',
    appId: '1:811652518412:android:57808c2f7fc4c56a3e9429',
    messagingSenderId: '811652518412',
    projectId: 'flash-chat-f2ed3',
    storageBucket: 'flash-chat-f2ed3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJTfxZuPvgwj0LI9gePvNf2sKdIDi3BLY',
    appId: '1:811652518412:ios:a90c42b024e2261f3e9429',
    messagingSenderId: '811652518412',
    projectId: 'flash-chat-f2ed3',
    storageBucket: 'flash-chat-f2ed3.appspot.com',
    iosClientId: '811652518412-gkh8jdprcktic3mr4aq3v0bqg5pmenvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatStartingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJTfxZuPvgwj0LI9gePvNf2sKdIDi3BLY',
    appId: '1:811652518412:ios:a90c42b024e2261f3e9429',
    messagingSenderId: '811652518412',
    projectId: 'flash-chat-f2ed3',
    storageBucket: 'flash-chat-f2ed3.appspot.com',
    iosClientId: '811652518412-gkh8jdprcktic3mr4aq3v0bqg5pmenvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatStartingProject',
  );
}
